version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /C/Users/khouloud/Desktop/Django/denv/base:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  dashbord-backend:
    build:
      context: .
      dockerfile: Dockerfile
    #image: dashboard-backend
    restart: always
    environment:
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=dashboard_db
    ports:
      - "8000:8000"
  dashbord-frontend:
    build:
      context: ../dashboard_frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4200:4200"
