version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
  dashbord-backend:
    build:
      context: .
      dockerfile: Dockerfile
    #image: dashboard-backend
    restart: always
    environment:
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=dashboard_db
    ports:
      - "8000:8000"
volumes:
  db:
    driver: local
